spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/first_db"
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
server:
  address: localhost
  port: 8080

age:
  min: 18
  max: 100