CREATE TABLE Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name varchar(100) NOT NULL,
                       age int,
                       email varchar(100)
);

INSERT INTO Person (name, age, email) VALUES ('Taras',23,'rar@gmail.com');
INSERT INTO Person (name, age, email) VALUES ('Grigoriy',33,'grigoriy@gmail.com');
INSERT INTO Person (name, age, email) VALUES ('Paraska',77,'babka@gmail.com');